//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oku_Yaz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kelimeler_D
    {
        public int Kelimeler_DId { get; set; }
        public string Kelimeler_D1 { get; set; }
    }
}
