//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oku_Yaz
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KelimelerEntities1 : DbContext
    {
        public KelimelerEntities1()
            : base("name=KelimelerEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Esyalar> Esyalar { get; set; }
        public virtual DbSet<Hayvanlar> Hayvanlar { get; set; }
        public virtual DbSet<Kelimeler_D> Kelimeler_D { get; set; }
        public virtual DbSet<Meslekler> Meslekler { get; set; }
        public virtual DbSet<Teknoloji> Teknoloji { get; set; }
        public virtual DbSet<WordCount> WordCounts { get; set; }
    }
}
