//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oku_Yaz
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordCount
    {
        public int ID { get; set; }
        public Nullable<int> WordCount1 { get; set; }
        public string Name { get; set; }
        public string password { get; set; }
    }
}
